/** Codes pays internes (seed WC2026) → TLA football-data.org */
export const OUR_CODE_TO_FOOTBALL_DATA_TLA: Record<string, string> = {
  MX: "MEX",
  ZA: "RSA",
  KR: "KOR",
  CZ: "CZE",
  CA: "CAN",
  BA: "BIH",
  QA: "QAT",
  CH: "SUI",
  BR: "BRA",
  MA: "MAR",
  HT: "HAI",
  "GB-SCT": "SCO",
  US: "USA",
  PY: "PAR",
  AU: "AUS",
  TR: "TUR",
  DE: "GER",
  CW: "CUW",
  CI: "CIV",
  EC: "ECU",
  NL: "NED",
  JP: "JPN",
  SE: "SWE",
  TN: "TUN",
  BE: "BEL",
  EG: "EGY",
  IR: "IRN",
  NZ: "NZL",
  ES: "ESP",
  CV: "CPV",
  SA: "KSA",
  UY: "URU",
  FR: "FRA",
  SN: "SEN",
  NO: "NOR",
  IQ: "IRQ",
  AR: "ARG",
  DZ: "ALG",
  AT: "AUT",
  JO: "JOR",
  PT: "POR",
  CD: "COD",
  UZ: "UZB",
  CO: "COL",
  "GB-ENG": "ENG",
  HR: "CRO",
  GH: "GHA",
  PA: "PAN",
};

export function footballDataTlaForOurCode(code: string | null | undefined): string | null {
  if (!code) return null;
  const key = code.trim().toUpperCase();
  return OUR_CODE_TO_FOOTBALL_DATA_TLA[key] ?? key.replace("GB-", "");
}
